'use strict';
const $=s=>document.querySelector(s);
document.addEventListener('DOMContentLoaded',()=>{const nav=$('.nav'),toggle=$('.menu-toggle');if(toggle)toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});if(window.location.pathname.endsWith('analyze.html'))initAnalyze();if(window.location.pathname.endsWith('marketplace.html'))renderMarketplace();if(window.location.pathname.endsWith('services.html'))renderServices();if(window.location.pathname.endsWith('impact.html'))renderImpact();if(window.location.pathname.endsWith('upcycle.html'))initUpcycle();});
function initAnalyze(){Object.entries(demoData.scenarios).forEach(([key,item])=>{const b=document.createElement('button');b.className='scenario';b.type='button';b.dataset.key=key;b.textContent=item.emoji+' '+item.label;b.addEventListener('click',()=>selectScenario(key));$('#scenarios').append(b)});const input=$('#fileInput'),drop=$('#dropzone');input.addEventListener('change',e=>showFile(e.target.files[0]));['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>showFile(e.dataTransfer.files[0]));}
function selectScenario(key){const item=demoData.scenarios[key];document.querySelectorAll('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.key===key));$('#resultTitle').textContent=item.emoji+' '+item.label;$('#resultTag').textContent=item.tag;$('#results').innerHTML=`<article class="card result-card"><span class="score">${item.score}</span><h3>Reuse potential</h3><p>${item.summary}</p></article>`+item.cards.map(c=>`<article class="card result-card"><span class="tag">${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p></article>`).join('');}
function showFile(file){if(!file)return;if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}$('#fileName').textContent=file.name+' · '+Math.round(file.size/1024)+' KB';$('#preview').src=URL.createObjectURL(file);$('#preview').style.display='block';selectScenario('clutter');}
function renderMarketplace(){const target=$('#marketGrid');target.innerHTML=demoData.marketplace.map(x=>`<article class="card market-card"><div class="visual">${x[1]}</div><h3>${x[0]}</h3><p>${x[3]}</p><div class="price">${x[2]}</div><button class="secondary" type="button" onclick="alert('Preview only — no message is sent.')">View listing</button></article>`).join('');}
function renderServices(){const target=$('#serviceGrid');target.innerHTML=demoData.services.map(x=>`<article class="card service-card"><div class="visual">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p><small>${x[3]}</small><br><button class="secondary" type="button" onclick="alert('This is a preview action — no booking is made.')">Explore service</button></article>`).join('');}
function renderImpact(){const target=$('#impactGrid');target.innerHTML=demoData.impact.map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');}
function initUpcycle(){const search=$('#ideaSearch'),filter=$('#ideaFilter'),dialog=$('#tutorialDialog'),dialogContent=$('#dialogContent'),dialogClose=$('#dialogClose');function openTutorial(i){dialogContent.innerHTML=`<span class="tag">${i.object}</span><h2 id="dialogTitle">${i.emoji} ${i.name}</h2><p>${i.purpose}</p><div class="tutorial-meta"><strong>${i.meta}</strong></div><h3>What you need</h3><p>${i.materials}</p><h3>How to make it</h3><ol>${i.steps.map(s=>'<li>'+s+'</li>').join('')}</ol><div class="safety-box"><strong>Safety tips</strong><p>${i.safety}</p></div><div class="refs"><strong>Reference:</strong> ${i.refs.map(r=>`<a href="${r[1]}" target="_blank" rel="noreferrer">${r[0]}</a>`).join(' · ')}</div>`;dialog.showModal();}function render(){const q=search.value.toLowerCase().trim(),f=filter.value;const list=demoData.ideas.filter(i=>(!f||i.object===f)&&(i.name+' '+i.object+' '+i.meta+' '+i.purpose).toLowerCase().includes(q));$('#ideaCount').textContent=list.length+' tutorial'+(list.length===1?'':'s')+' found';$('#ideasGrid').innerHTML=list.map((i,n)=>`<button class="card idea-card idea-button" type="button" data-idea="${demoData.ideas.indexOf(i)}"><div class="visual">${i.emoji}</div><div><span class="tag">${i.object}</span><h3>${i.name}</h3><p>${i.purpose}</p><div class="idea-preview"><strong>${i.meta}</strong><br><span>Materials, steps, and safety guide →</span></div></div></button>`).join('')||'<p class="section-intro">No tutorials match. Try “easy”, “bottle”, or choose All items.</p>';document.querySelectorAll('[data-idea]').forEach(button=>button.addEventListener('click',()=>openTutorial(demoData.ideas[button.dataset.idea])));}search.addEventListener('input',render);filter.addEventListener('change',render);dialogClose.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});render();}
