'use strict';
const demoData={
scenarios:{chair:{label:'Wooden chair',emoji:'🪑',tag:'Repair + reuse',summary:'A sturdy chair can become a welcoming seat, plant stand, or community giveaway.',score:'92%',cards:[['Material read','Solid wood · hardware intact','Good candidate for repair'],['Best next step','Tighten joints and sand','30–60 minutes'],['Keep it moving','List it for a neighbour','High local demand']]},bottle:{label:'Plastic bottle',emoji:'🧴',tag:'Creative reuse',summary:'A clean bottle can become a self-watering planter or compact storage.',score:'78%',cards:[['Material read','PET plastic · lightweight','Wash before reuse'],['Best next step','Cut with adult supervision','20 minutes'],['Keep it moving','Bundle for recycling','Check local rules']]},water:{label:'Water bottle',emoji:'🚰',tag:'Refill + reuse',summary:'Give a durable water bottle a longer life with a deep clean and replacement lid.',score:'88%',cards:[['Material read','Reusable bottle','Check for odour or cracks'],['Best next step','Replace the seal','10 minutes'],['Keep it moving','Pass it to a friend','Easy handoff']]},mat:{label:'Mat',emoji:'🧶',tag:'Repair + refresh',summary:'A worn mat can be cleaned, edged, or transformed into a cosy pet mat.',score:'84%',cards:[['Material read','Textile / rubber blend','Dry fully after cleaning'],['Best next step','Trim and bind edges','45 minutes'],['Keep it moving','Donate to a shelter','Useful locally']]},pins:{label:'Hair pins',emoji:'📌',tag:'Organise + craft',summary:'Loose hair pins are tiny, but a neat holder keeps them useful and out of the waste stream.',score:'73%',cards:[['Material read','Metal + coating','Separate damaged pieces'],['Best next step','Make a pin keeper','15 minutes'],['Keep it moving','Share a small bundle','Easy to post']]},clutter:{label:'Clutter',emoji:'📦',tag:'Sort + share',summary:'A five-minute sort can reveal useful items for reuse, repair, or responsible recycling.',score:'81%',cards:[['Material read','Mixed materials','Sort before discarding'],['Best next step','Make 3 clear piles','15 minutes'],['Keep it moving','List one bundle','Less overwhelm']]}},
marketplace:[['Neighbourhood chair','🪑','Free · 2 km away','A solid chair looking for a reading corner.'],['Clean bottle bundle','🧴','$3 · Pickup today','Six washed bottles for a balcony garden.'],['Patchwork mat','🧶','Swap','Handmade mat in exchange for spare fabric.'],['Desk organiser set','📦','$5 · Community shelf','Small containers ready for a tidy workspace.'],['Garden cuttings','🌱','Free · Saturday pickup','Healthy herb cuttings in reused pots.'],['Repairable lamp','💡','$8 · Needs a new cord','A classic lamp for someone who enjoys fixing things.']],
services:[['Repair corner','🔧','Book a 30-minute fix with a local maker.','Bring a photo and the loose or broken part.'],['Community pickup','🚲','Schedule a shared pickup for useful items.','Neighbourhood routes run on Tuesdays and Saturdays.'],['Learn together','🧵','Join a small workshop and build confidence.','Friendly sessions cover sewing, sanding, and sorting.'],['Reuse concierge','🗂️','Get help choosing donate, repair, or recycle.','A practical 15-minute decision guide for busy homes.'],['Tool library','🛠️','Borrow the right tool instead of buying one.','Demo catalogue includes drills, clamps, and safety gear.'],['Material drop-off','♻️','Find a sensible next home for sorted materials.','Staff can explain the local-style demo streams.']],
impact:[['12','items given a second life'],['8.4 kg','estimated waste avoided'],['6','local handoffs completed'],['4','repair skills practised'],['3','new neighbours met'],['18','refill days logged']],
ideas:[
{name:'Window-box herb planter',object:'Plastic bottle',emoji:'🪴',meta:'20 min · Easy',purpose:'Turn a cleaned bottle into a bright, low-water herb planter.',materials:'Bottle, scissors, marker, potting mix, herb cutting',steps:['Mark and carefully cut an opening with an adult nearby.','Add drainage holes, then fill with soil and a cutting.','Label it and place it somewhere with gentle light.'],safety:'Wash thoroughly; cover sharp edges with tape and never leave cutting tools unattended.',refs:[['EPA plastic reuse guidance','https://www.epa.gov/recycle']]},
{name:'Refill station',object:'Water bottle',emoji:'💧',meta:'10 min · Easy',purpose:'Make reuse the default by pairing a bottle with a visible refill reminder.',materials:'Bottle, replacement seal if needed, washable label',steps:['Inspect the bottle and replace any cracked seal.','Clean according to its care instructions.','Add a “refill me” label and keep it by your keys.'],safety:'Do not reuse bottles that are damaged, cloudy, or not food-safe.',refs:[['FDA food contact basics','https://www.fda.gov/food']]},
{name:'Calm reading chair',object:'Chair',emoji:'🪑',meta:'60 min · Medium',purpose:'Refresh a sound chair with a light sand, warm oil, and a new cushion.',materials:'Fine sandpaper, cloth, wood oil, cushion or fabric',steps:['Check every joint and tighten loose screws.','Sand only rough spots, following the grain.','Wipe clean, apply oil as directed, and add a washable cushion.'],safety:'Wear eye protection and a dust mask while sanding; ventilate finishes.',refs:[['Woodworking safety basics','https://www.osha.gov/woodworking']]},
{name:'No-sew pet mat',object:'Mat',emoji:'🐾',meta:'45 min · Easy',purpose:'Give a faded mat a second life as a soft, washable pet rest.',materials:'Clean mat, fabric scissors, non-slip backing, fabric strips',steps:['Wash and dry the mat completely.','Trim frayed edges and bind them with fabric strips.','Add non-slip backing, then test on a clear floor.'],safety:'Avoid loose strings around pets; choose non-toxic, washable materials.',refs:[['ASPCA household safety','https://www.aspca.org/pet-care']]},
{name:'Pin-pocket organiser',object:'Hair pins',emoji:'🧷',meta:'15 min · Easy',purpose:'A tiny fabric pocket makes hair pins visible and keeps drawers calm.',materials:'Scrap fabric, thread or fabric glue, button, hair pins',steps:['Fold fabric into a pocket and secure the sides.','Add a button or simple closure.','Sort pins by type and keep the organiser near your mirror.'],safety:'Handle needles carefully and keep small pieces away from young children.',refs:[['Textile reuse ideas','https://www.unep.org/']]},
{name:'Clutter-to-care bundle',object:'Clutter',emoji:'📦',meta:'15 min · Easy',purpose:'Create one useful bundle instead of six stressful piles.',materials:'Box, labels, marker, phone camera',steps:['Sort into keep, share, repair, and recycle.','Photograph and label one share bundle.','Offer it locally, then take remaining items to the right stream.'],safety:'Do not donate recalled, broken, or unsafe electrical items.',refs:[['Consumer product recalls','https://www.cpsc.gov/Recalls']]}]};
